FROM golang:bullseye

# Set the working directory
WORKDIR /app

RUN go mod init minitwit 

#RUN go install github.com/cosmtrek/air@latest

# Copy the server code into the container
COPY go.mod ./
COPY go.sum ./

RUN go mod download
RUN go mod tidy

COPY src app/src

# Make port 8080 available to the host
EXPOSE 8080

# Build and run the server when the container is started
#RUN go build /app/server.go
#ENTRYPOINT ./server


WORKDIR /app/src

CMD ["/app/server"]